#!/bin/sh
find . -name '*.java' -exec sed -i -e '
s/\/\* private static final Logger trace = Logger\.getLogger(\(.*\)); \*\//private static final java.util.logging.Logger trace = java.util.logging.Logger\.getLogger(\1);/
s/\/\*\(trace\.fine.*;\)\*\//\1/
/trace\.fine/{
N
s/\/\*\(trace\.fine.*;\)\*\//\1/
}' {} \;

